### ISSUE TITLE
App crashed frequently on didRegisterForRemoteNotificationsWithDeviceToken

### ISSUE THREAD

**Issue by NishanthMurugan** [Marketing-Suite/ios-sdk#5]
This crash is specifically happening after updating to SDK 1.2.0. Please find the crash log and screenshots attached below 

**Crashed: com.apple.main-thread
0  EMSMobileSDK                   0x1009347d4 _TTSf4g_g_n___TFC12EMSMobileSDK12EMSMobileSDK9SubscribefzT11deviceTokenV10Foundation4Data17completionHandlerGSqFSST___T_ + 3004
1  EMSMobileSDK                   0x10092efc0 _TToFC12EMSMobileSDK12EMSMobileSDK9SubscribefzT11deviceTokenV10Foundation4Data17completionHandlerGSqFSST___T_ + 156
2  reader-app                0x10007806c -[AppDelegate application:didRegisterForRemoteNotificationsWithDeviceToken:] (AppDelegate.m:157)**

<img width="1440" alt="screen shot 2017-09-05 at 4 11 02 pm" src="https://user-images.githubusercontent.com/30654850/30382685-6ecd0eb2-98bd-11e7-8886-998d6f7db1c9.png">

Note: Crash is not reproducible on development mode. But It is happening on production frequently.

**Comment by ClientDeveloperRelations** [comment]
Hi @NishanthMurugan , this has been fixed in the latest release.  Please Let us know when you've had a chance to test & confirm.
